import { getSlugFromEntry, normalizeSlug } from '@/utils/navigation';
import { getCollection } from 'astro:content';
import type { CollectionEntry } from 'astro:content';

export type DocsEntry = CollectionEntry<'docs'>;

function getEntryLabel(entry: DocsEntry): string {
  return entry.filePath || entry.id;
}

function getParentRoutes(slug: string): string[] {
  const segments = normalizeSlug(slug)
    .replace(/^\/docs\/?/, '')
    .replace(/^\/+|\/+$/g, '')
    .split('/')
    .filter(Boolean);

  return segments
    .slice(0, -1)
    .map((_, index) => `/docs/${segments.slice(0, index + 1).join('/')}/`);
}

function validatePublishedDocs(entries: DocsEntry[]): void {
  const entriesByRoute = new Map<string, DocsEntry>();

  for (const entry of entries) {
    const route = normalizeSlug(getSlugFromEntry(entry));
    const existingEntry = entriesByRoute.get(route);

    if (existingEntry) {
      throw new Error(
        `Duplicate docs route "${route}" generated by "${getEntryLabel(existingEntry)}" and "${getEntryLabel(entry)}".`,
      );
    }

    entriesByRoute.set(route, entry);
  }

  if (entries.length > 0 && !entriesByRoute.has('/docs/')) {
    throw new Error('Missing docs home entry. Expected src/content/docs/index.md or index.mdx.');
  }

  for (const [route, entry] of entriesByRoute) {
    for (const parentRoute of getParentRoutes(route)) {
      if (!entriesByRoute.has(parentRoute)) {
        throw new Error(
          `Docs entry "${getEntryLabel(entry)}" requires a published parent entry for "${parentRoute}".`,
        );
      }
    }
  }
}

export async function getPublishedDocs(): Promise<DocsEntry[]> {
  const docs = await getCollection('docs', entry => !entry.data.draft);
  validatePublishedDocs(docs);
  return docs;
}

export async function getPublishedDocsBySlug(): Promise<Map<string, DocsEntry>> {
  const docs = await getPublishedDocs();
  return new Map(docs.map(entry => [normalizeSlug(getSlugFromEntry(entry)), entry]));
}

export async function getDocsTitleBySlug(): Promise<Map<string, string>> {
  const docs = await getPublishedDocs();
  return new Map(
    docs.map(entry => [
      normalizeSlug(getSlugFromEntry(entry)),
      entry.data.sidebar?.label || entry.data.title,
    ]),
  );
}

export function getDocsRouteParam(entry: DocsEntry): string | null {
  const slug = getSlugFromEntry(entry);
  if (normalizeSlug(slug) === '/docs/') {
    return null;
  }

  const paramsSlug = slug
    .replace(/^\/docs\/?/, '')
    .replace(/^\/+/, '')
    .replace(/\/+$/, '');

  return paramsSlug || null;
}
