import { getCollection, type CollectionEntry } from 'astro:content';

export type DocsEntry = CollectionEntry<'docs'>;

export interface DocsNavItem {
  title: string;
  href: string;
  description?: string;
  badge?: string;
  order: number;
  children?: DocsNavItem[];
}

export interface DocsSection {
  title: string;
  href: string;
  description?: string;
  badge?: string;
  order: number;
  items: DocsNavItem[];
}

export interface DocsPageLink {
  href: string;
  title: string;
  description?: string;
}

export interface DocsBreadcrumb {
  title: string;
  href: string;
}

export const DOCS_ROOT = '/docs/';

const FALLBACK_ORDER = 999;

/* ------------------------------------------------------------------------- */
/* Paths                                                                     */
/* ------------------------------------------------------------------------- */

function segmentsToPath(segments: readonly string[]): string {
  return segments.length === 0 ? DOCS_ROOT : `${DOCS_ROOT}${segments.join('/')}/`;
}

/** Split any docs path or collection id into its segments below `/docs/`. */
export function docsPathSegments(pathOrId: string): string[] {
  const segments = pathOrId
    .replace(/\.(md|mdx)$/i, '')
    .split('/')
    .filter(Boolean);

  if (segments[0] === 'docs') segments.shift();
  if (segments.at(-1) === 'index') segments.pop();

  return segments;
}

/** Canonical route for a docs path or collection id: always `/docs/…/` with a trailing slash. */
export function normalizeDocsPath(pathOrId: string): string {
  return segmentsToPath(docsPathSegments(pathOrId));
}

/** Route of a collection entry, derived from its id (`install/iso` → `/docs/install/iso/`). */
export function docsEntryPath(entry: Pick<DocsEntry, 'id'>): string {
  return normalizeDocsPath(entry.id);
}

/** Top-level section key of a docs path (`/docs/install/iso/` → `install`), or `null` for the docs home. */
export function docsSectionKey(path: string): string | null {
  return docsPathSegments(path)[0] ?? null;
}

/** `[...slug]` route param for an entry, or `null` for the docs home which has its own page. */
export function docsRouteParam(entry: Pick<DocsEntry, 'id'>): string | null {
  const segments = docsPathSegments(entry.id);
  return segments.length > 0 ? segments.join('/') : null;
}

/** Human-readable fallback label for a path segment. */
export function humanizeSegment(segment: string): string {
  if (segment.toLowerCase() === 'faq') return 'FAQ';

  return segment
    .split('-')
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

/* ------------------------------------------------------------------------- */
/* Entries                                                                   */
/* ------------------------------------------------------------------------- */

function entryLabel(entry: DocsEntry): string {
  return entry.filePath ?? entry.id;
}

function entryOrder(entry: DocsEntry): number {
  return entry.data.sidebar?.order ?? entry.data.order ?? FALLBACK_ORDER;
}

function entryTitle(entry: DocsEntry): string {
  return entry.data.sidebar?.label ?? entry.data.title;
}

function assertValidDocs(entries: DocsEntry[]): Map<string, DocsEntry> {
  const byPath = new Map<string, DocsEntry>();

  for (const entry of entries) {
    const path = docsEntryPath(entry);
    const existing = byPath.get(path);
    if (existing) {
      throw new Error(
        `Duplicate docs route "${path}" generated by "${entryLabel(existing)}" and "${entryLabel(entry)}".`,
      );
    }
    byPath.set(path, entry);
  }

  if (entries.length > 0 && !byPath.has(DOCS_ROOT)) {
    throw new Error('Missing docs home entry. Expected src/content/docs/index.md or index.mdx.');
  }

  for (const [path, entry] of byPath) {
    const segments = docsPathSegments(path);
    for (let depth = 1; depth < segments.length; depth += 1) {
      const parentPath = segmentsToPath(segments.slice(0, depth));
      if (!byPath.has(parentPath)) {
        throw new Error(
          `Docs entry "${entryLabel(entry)}" requires a published parent entry for "${parentPath}".`,
        );
      }
    }
  }

  return byPath;
}

let docsIndexPromise: Promise<Map<string, DocsEntry>> | undefined;

/** Published docs entries keyed by route. Validated once and cached for the lifetime of the build. */
export function getDocsIndex(): Promise<Map<string, DocsEntry>> {
  docsIndexPromise ??= getCollection('docs', entry => !entry.data.draft).then(assertValidDocs);
  return docsIndexPromise;
}

export async function getDocsEntries(): Promise<DocsEntry[]> {
  return [...(await getDocsIndex()).values()];
}

/* ------------------------------------------------------------------------- */
/* Navigation tree                                                           */
/* ------------------------------------------------------------------------- */

function compareNav(
  a: { order: number; title: string },
  b: { order: number; title: string },
): number {
  return a.order - b.order || a.title.localeCompare(b.title);
}

function toNavItem(entry: DocsEntry): DocsNavItem {
  return {
    title: entryTitle(entry),
    href: docsEntryPath(entry),
    description: entry.data.description,
    badge: entry.data.sidebar?.badge,
    order: entryOrder(entry),
  };
}

function isListed(entry: DocsEntry): boolean {
  return entry.data.sidebar?.hidden !== true;
}

function groupBy<T>(items: T[], key: (item: T) => string | undefined): Map<string, T[]> {
  const groups = new Map<string, T[]>();
  for (const item of items) {
    const groupKey = key(item);
    if (groupKey === undefined) continue;
    const group = groups.get(groupKey);
    if (group) group.push(item);
    else groups.set(groupKey, [item]);
  }
  return groups;
}

/**
 * Items of one section. Direct children of the section become items; deeper entries are
 * grouped under their first sub-segment, with a synthetic group when no index page exists.
 */
function buildSectionItems(section: string, entries: DocsEntry[]): DocsNavItem[] {
  const groups = groupBy(entries, entry => docsPathSegments(entry.id)[1]);
  const items: DocsNavItem[] = [];

  for (const [groupKey, groupEntries] of groups) {
    const groupIndex = groupEntries.find(entry => docsPathSegments(entry.id).length === 2);
    const children = groupEntries
      .filter(entry => docsPathSegments(entry.id).length > 2)
      .map(toNavItem)
      .sort(compareNav);

    if (groupIndex) {
      const item = toNavItem(groupIndex);
      items.push(children.length > 0 ? { ...item, children } : item);
    } else if (children.length > 0) {
      items.push({
        title: humanizeSegment(groupKey),
        href: segmentsToPath([section, groupKey]),
        order: children[0]?.order ?? FALLBACK_ORDER,
        children,
      });
    }
  }

  return items.sort(compareNav);
}

function buildTree(index: Map<string, DocsEntry>): DocsSection[] {
  const listed = [...index.values()].filter(isListed);
  const home = index.get(DOCS_ROOT);
  const sections: DocsSection[] = [];

  if (home && isListed(home)) {
    sections.push({ ...toNavItem(home), items: [] });
  }

  const bySection = groupBy(listed, entry => docsPathSegments(entry.id)[0]);
  const regularSections: DocsSection[] = [];

  for (const [section, entries] of bySection) {
    const sectionIndex = entries.find(entry => docsPathSegments(entry.id).length === 1);
    const items = buildSectionItems(
      section,
      entries.filter(entry => docsPathSegments(entry.id).length > 1),
    );
    const base: Omit<DocsSection, 'items'> = sectionIndex
      ? toNavItem(sectionIndex)
      : {
          title: humanizeSegment(section),
          href: segmentsToPath([section]),
          order: items[0]?.order ?? FALLBACK_ORDER,
        };

    regularSections.push({ ...base, items });
  }

  return [...sections, ...regularSections.sort(compareNav)];
}

let docsTreePromise: Promise<DocsSection[]> | undefined;

/** Sidebar tree: the docs home first, then every section sorted by frontmatter `order`. */
export function getDocsTree(): Promise<DocsSection[]> {
  docsTreePromise ??= getDocsIndex().then(buildTree);
  return docsTreePromise;
}

/* ------------------------------------------------------------------------- */
/* Page helpers                                                              */
/* ------------------------------------------------------------------------- */

function flattenTree(sections: DocsSection[]): DocsPageLink[] {
  const pages: DocsPageLink[] = [];
  const seen = new Set<string>();

  const push = (item: Pick<DocsNavItem, 'href' | 'title' | 'description'>) => {
    if (seen.has(item.href)) return;
    seen.add(item.href);
    pages.push({ href: item.href, title: item.title, description: item.description });
  };

  const walk = (items: DocsNavItem[]) => {
    for (const item of items) {
      push(item);
      if (item.children) walk(item.children);
    }
  };

  for (const section of sections) {
    push(section);
    walk(section.items);
  }

  return pages;
}

/** Previous and next pages in reading order, following the sidebar tree. */
export async function getDocsPagination(
  path: string,
): Promise<{ prev: DocsPageLink | null; next: DocsPageLink | null }> {
  const pages = flattenTree(await getDocsTree());
  const current = normalizeDocsPath(path);
  const index = pages.findIndex(page => page.href === current);

  if (index < 0) return { prev: null, next: null };

  return {
    prev: pages[index - 1] ?? null,
    next: pages[index + 1] ?? null,
  };
}

/** Breadcrumb trail from the docs home to `path`, using page titles where an entry exists. */
export async function getDocsBreadcrumbs(path: string): Promise<DocsBreadcrumb[]> {
  const index = await getDocsIndex();
  const segments = docsPathSegments(path);
  const crumbs: DocsBreadcrumb[] = [];

  for (let depth = 0; depth <= segments.length; depth += 1) {
    const href = segmentsToPath(segments.slice(0, depth));
    const entry = index.get(href);
    const title = entry
      ? entryTitle(entry)
      : depth === 0
        ? 'Home'
        : humanizeSegment(segments[depth - 1]!);
    crumbs.push({ title, href });
  }

  return crumbs;
}
